# Generated by Django 4.2.6 on 2023-10-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_store', '0005_alter_autoparts_tel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoparts',
            name='tel_number',
        ),
    ]
