# Generated by Django 4.2.6 on 2023-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_store', '0006_remove_autoparts_tel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='Email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Укажите вашу почту'),
        ),
        migrations.AddField(
            model_name='autoparts',
            name='tel_number',
            field=models.IntegerField(null=True, verbose_name='Укажите номер телефона'),
        ),
    ]
