# Generated by Django 4.2.6 on 2023-10-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_store', '0007_autoparts_email_autoparts_tel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('rate_numbers', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐⭐⭐⭐')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('select_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_product', to='auto_parts_store.autoparts')),
            ],
        ),
    ]
