# Generated by Django 4.2.6 on 2023-10-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_store', '0008_reviewproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproducts',
            name='сondition',
            field=models.TextField(null=True),
        ),
    ]
