# Generated by Django 4.2.6 on 2023-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_store', '0009_reviewproducts_сondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewproducts',
            name='rate_numbers',
        ),
        migrations.AddField(
            model_name='reviewproducts',
            name='rate_stars',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐⭐⭐⭐')], max_length=20, null=True, verbose_name='Поставьте рейтинг'),
        ),
        migrations.AlterField(
            model_name='reviewproducts',
            name='text_comment',
            field=models.TextField(max_length=100, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reviewproducts',
            name='сondition',
            field=models.TextField(null=True, verbose_name='Состояние товара'),
        ),
    ]
