# Generated by Django 4.2.6 on 2023-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_store', '0010_remove_reviewproducts_rate_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproducts',
            name='text_comment',
            field=models.TextField(max_length=500, verbose_name='Комментарий'),
        ),
    ]
