# Generated by Django 4.2.6 on 2023-10-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parts_store', '0011_alter_reviewproducts_text_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewproducts',
            name='сondition',
            field=models.TextField(blank=True, verbose_name='Состояние товара'),
        ),
    ]
