# Generated by Django 4.2.6 on 2023-10-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_technodomproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnoDomProducts',
            new_name='SulpakProducts',
        ),
    ]
