# Generated by Django 4.2.6 on 2023-10-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_rename_technodomproducts_sulpakproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sulpakproducts',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
