# Generated by Django 4.2.6 on 2023-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_post_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
